### ISSUE TITLE
Download sources

### ISSUE THREAD

**Issue by KoSchuX** [yizhak-lab-ccg/RNA_MUTECt_WMN#1]
In Section "Running instructions" ( https://github.com/yizhak-lab-ccg/RNA_MUTECt_WMN#running-instructions ) the download source for 'call_stats_capture_paper_v1_3.tsv', 'maf_file_rna_final_paper_v1_3.tsv', the pon binary files and reference files is unclear. Providing direct links or further description of download procedure would be useful.

**Comment by noamrud** [comment]
Added
