### ISSUE TITLE
Specify Requirements

### ISSUE THREAD

**Issue by KoSchuX** [yizhak-lab-ccg/RNA_MUTECt_WMN#2]
In section "Requirements" ( https://github.com/yizhak-lab-ccg/RNA_MUTECt_WMN#requirements ) stating the minimal required versions would be helpful to evade possible version conflicts. A good example is https://github.com/broadinstitute/RNA_MUTECT_1.0-1

**Comment by noamrud** [comment]
Added, thanks.
