### ISSUE TITLE
File download location & reference version of Funcotator

### ISSUE THREAD

**Issue by ttab963** [yizhak-lab-ccg/RNA_MUTECt_WMN#3]
Hello.

I tried to follow your instruction, but still i cannot know where can i get those two files :

call_stats_capture_paper_v1_3.tsv
maf_file_rna_final_paper_v1_3.tsv

Other PON & reference can be prepared from ourselves.

Plus, I saw in the RNA-Mutect-WMN.py code that Funcotator use hg19.
If I change this part to hg38, could it make problems in downstream code?

Thanks.

**Comment by noamrud** [comment]
Hi,
These files are output of RNA-MuTect ([https://github.com/broadinstitute/RNA_MUTECT_1.0-1](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbroadinstitute%2FRNA_MUTECT_1.0-1&data=05%7C01%7Cnoam.rudberg%40campus.technion.ac.il%7C80e4ea840552431de62e08da545c02bb%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637915051431452524%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EbRCoiw9iF%2FqLcwK4SUZ7Z2A3HnrHX6mB6UXQNcd99w%3D&reserved=0)). A cloud implementation can be found in Terra: [https://app.terra.bio/#workspaces/broad-firecloud-gtex/RNA_MuTect](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.terra.bio%2F%23workspaces%2Fbroad-firecloud-gtex%2FRNA_MuTect&data=05%7C01%7Cnoam.rudberg%40campus.technion.ac.il%7C80e4ea840552431de62e08da545c02bb%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637915051431452524%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FEOdtXd8rZFmiyKUxHOoqsS%2BEXE3ShQzX%2FVnGKYXnJs%3D&reserved=0)).

Regarding Funcotator version: it should be ok, but you'll also need to remove the `--force-b37-to-hg19-reference-contig-conversion` flag.
