### ISSUE TITLE
Need for RNA-Mutect for WMN

### ISSUE THREAD

**Issue by pinunQ** [yizhak-lab-ccg/RNA_MUTECt_WMN#4]
Hello, 

I want to use your approach but I have a confusion can we use RNA-Mutect on samples without matched normal because it seems that is a requirement for running RNA-mutect to get input files for RNA-Mutect-WMN

**Comment by noamrud** [comment]
Hi @pinunQ, 
In order to run RNA-MuTect any normal sample can be used and it does not require the matched-normal sample.

**Comment by pinunQ** [comment]
Hi, 

Thank you for your response.

Sorry to reopen the issue again but I am facing few problems in running filtering steps as I do not have MATLAB resource at my lab so is there a run around to that? 

What I mean is that instead of using MATLAB for running filtration can I use some other scripts (python, snakemake or others..)

Also can you share the command line argument for HISAT2 alignment step which you followed during the pipeline.

**Comment by noamrud** [comment]
Hi @pinunQ ,
The only way to avoid running Matlab for RNA-MuTect is to run the pipeline through its cloud implementation on Terra:
[https://app.terra.bio/#workspaces/broad-firecloud-gtex/RNA_MuTect](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.terra.bio%2F%23workspaces%2Fbroad-firecloud-gtex%2FRNA_MuTect&data=05%7C01%7Cnoam.rudberg%40campus.technion.ac.il%7C21f9a7c4756f44bcf17808da6558c4b3%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637933729190013909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CnYTba1T5n5R4lAsFwgiSMCY2eQlTXccqEq8uqDk4A8%3D&reserved=0)

**Comment by pinunQ** [comment]
Hi,
I tried to use workspace and it requires access how am I supposed to run there?

Please help!!
Thank you
